# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Simon Blog
header-img: img/home-bg.jpg
email: songjia3000@163.com
description: ""
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://simonappboy.github.io" # the base hostname & protocol for your site
twitter_username: SimonAppBoy
github_username:  SimonAppBoy

# Build settings
highlighter: pygments
permalink: pretty
paginate: 10
markdown: kramdown
